/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef PARTICLE_RENDER_FS_HPP_
# define PARTICLE_RENDER_FS_HPP_

const char *particle_render_fs =
 "#version 420\n"
 "float s(float v,float s)"
 "{"
   "float i=s/4.*60.,f=15.,t=.8;"
   "return smoothstep(-f/2.,-f*(1.-t)/2.,-abs(v-i-f*.5));"
 "}"
 "vec3 s(float v)"
 "{"
   "float f=v+2.;"
   "vec3 s=vec3(f,f*f,f*f*f),t=fract(s*222.)+vec3(2.);"
   "return fract(s*t.yzx*t.zxy);"
 "}"
 "float v(float v)"
 "{"
   "return v/44100;"
 "}"
 "float f(float v)"
 "{"
   "return 1.-smoothstep(0.,4.,v);"
 "}"
 "float t(float v)"
 "{"
   "float f=60.-v;"
   "return 1.-smoothstep(0.,4.,f);"
 "}"
 "mat3 f(vec3 v,vec3 s)"
 "{"
   "vec3 f=normalize(v-s),t=normalize(cross(vec3(0.,1.,0.),f)),i=normalize(cross(f,t));"
   "mat3 c=mat3(t,i,f);"
   "return c;"
 "}"
 "uniform bool is_shadowmap;"
 "const mat4 i=mat4(1./1.5,0.,0.,0.,0.,1./1.5,0.,0.,0.,0.,-.4,0.,0.,0.,-1.4,1.);"
 "vec3 f()"
 "{"
   "return vec3(1.5,3.,2.);"
 "}"
 "mat3 s()"
 "{"
   "return f(f(),vec3(0.));"
 "}"
 "vec3 e(float v)"
 "{"
   "return is_shadowmap?f():vec3(.3,2.+cos(v),3.+sin(v)*.8);"
 "}"
 "mat3 e(float v,vec3 t)"
 "{"
   "return is_shadowmap?s():f(t,vec3(0.));"
 "}"
 "uniform float sample_count;"
 "layout(binding=1)uniform sampler2DShadow shadowmap;"
 "in vec3 vary_tangent,vary_view_dir;"
 "in vec4 vary_shadow_pos;"
 "in float vary_t,vary_nrm_insid;"
 "out vec4 color;"
 "vec3 c(float v)"
 "{"
   "vec3 f=fract(v+vec3(0.,2./3.,1./3.));"
   "f=abs(f*2.-1.);"
   "return clamp(f*3.-1.,0.,1.);"
 "}"
 "vec3 n(vec3 v)"
 "{"
   "return((c(v.x)-1.)*v.y+1.)*v.z;"
 "}"
 "vec3 c(float v,float f,float s)"
 "{"
   "return n(vec3(v,f,s));"
 "}"
 "void main()"
 "{"
   "float c=v(sample_count);"
   "vec3 i=normalize(vary_tangent),m=normalize(vary_view_dir);"
   "mat3 n=s();"
   "vec3 b=n[2];"
   "float r=dot(b,i),x=dot(m,i),d=sqrt(1.-r*r),g=pow(max(d*sqrt(1.-x*x)-r*x,0.),60.);"
   "color=d*vec4(.1,.05,.05,1.)+g*vec4(.4,.4,.4,1.)+vec4(.05);"
   "float p=textureProj(shadowmap,vary_shadow_pos);"
   "color*=p;"
   "color+=vec4(.05);"
   "color*=1.-max(f(c),t(c));"
   "color+=vec4(max(sin(vary_t*4.+c*6.+vary_nrm_insid*4.)-.9,0.)*10.);"
 "}";

#endif // PARTICLE_RENDER_FS_HPP_
