/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef PARTICLE_RENDER_VS_HPP_
# define PARTICLE_RENDER_VS_HPP_

const char *particle_render_vs =
 "#version 420\n"
 "float s(float f,float v)"
 "{"
   "float s=v/4.*60.,D=15.,g=.8;"
   "return smoothstep(-D/2.,-D*(1.-g)/2.,-abs(f-s-D*.5));"
 "}"
 "vec3 s(float v)"
 "{"
   "float f=v+2.;"
   "vec3 s=vec3(f,f*f,f*f*f),g=fract(s*222.)+vec3(2.);"
   "return fract(s*g.yzx*g.zxy);"
 "}"
 "float v(float v)"
 "{"
   "return v/44100;"
 "}"
 "float e(float v)"
 "{"
   "return 1.-smoothstep(0.,4.,v);"
 "}"
 "float t(float v)"
 "{"
   "float f=60.-v;"
   "return 1.-smoothstep(0.,4.,f);"
 "}"
 "mat3 e(vec3 f,vec3 v)"
 "{"
   "vec3 s=normalize(f-v),g=normalize(cross(vec3(0.,1.,0.),s)),t=normalize(cross(s,g));"
   "mat3 m=mat3(g,t,s);"
   "return m;"
 "}"
 "uniform bool is_shadowmap;"
 "const mat4 m=mat4(1./1.5,0.,0.,0.,0.,1./1.5,0.,0.,0.,0.,-.4,0.,0.,0.,-1.4,1.);"
 "vec3 e()"
 "{"
   "return vec3(1.5,3.,2.);"
 "}"
 "mat3 s()"
 "{"
   "return e(e(),vec3(0.));"
 "}"
 "vec3 n(float v)"
 "{"
   "return is_shadowmap?e():vec3(.3,2.+cos(v),3.+sin(v)*.8);"
 "}"
 "mat3 n(float v,vec3 f)"
 "{"
   "return is_shadowmap?s():e(f,vec3(0.));"
 "}"
 "const mat4 i=mat4(2.,0.,0.,0.,0.,3.55556,0.,0.,0.,0.,-1.0339,-1.,0.,0.,-.20339,0.);"
 "uniform float sample_count;"
 "layout(binding=0)uniform samplerBuffer positions;"
 "out vec3 vary_tangent,vary_view_dir;"
 "out vec4 vary_shadow_pos;"
 "out float vary_t,vary_nrm_insid;"
 "void main()"
 "{"
   "vec3 f=texelFetch(positions,gl_VertexID/2+gl_InstanceID*16+2).xyz,g=gl_VertexID/2==15?texelFetch(positions,gl_VertexID/2-1+gl_InstanceID*16+2).xyz:texelFetch(positions,gl_VertexID/2+1+gl_InstanceID*16+2).xyz,t=normalize(gl_VertexID/2==15?f-g:g-f);"
   "float p=v(sample_count);"
   "vec3 D=n(p);"
   "mat3 x=transpose(n(p,D));"
   "vec3 r=x*(f-D),c=x*t;"
   "r+=vec3(c.yx*vec2(1.,-1.)*float(gl_VertexID%2)*.001,0.);"
   "gl_Position=(is_shadowmap?m:i)*vec4(r,1.);"
   "vary_tangent=t;"
   "vary_view_dir=D-f;"
   "mat3 b=s(),d=transpose(b);"
   "vary_shadow_pos=m*vec4(d*(f-e()),1.);"
   "vary_shadow_pos.xyz*=.5;"
   "vary_shadow_pos.xyz+=.5;"
   "vary_shadow_pos.z-=.001;"
   "vary_t=gl_VertexID/2/16.;"
   "vary_nrm_insid=gl_InstanceID/20000.;"
 "}";

#endif // PARTICLE_RENDER_VS_HPP_
